name: resolve_tilde
description: A small and simple Dart package to quickly resolve tildes in multiple platforms.
version: 0.0.0
repository: https://github.com/Calebh101/dart_resolve_tilde

environment:
  sdk: ^3.8.1

dependencies:

dev_dependencies:
  lints: ^5.0.0

platforms:
  linux:
  macos:
  windows:
