name: resolve_tilde
description: A starting point for Dart libraries or applications.
version: 0.0.0
repository: https://github.com/Calebh101/dart_resolve_tilde

environment:
  sdk: ^3.8.1

dependencies:

dev_dependencies:
  lints: ^5.0.0
